In [1]:
import numpy as np

In [2]:
lst = [1, 2, 3, 4]
arr = np.array([1,2,3,4])
# print(arr)
print(arr)
print(lst)

[1 2 3 4]
[1, 2, 3, 4]


In [3]:
arr2 = np.arange(1,10)
print(arr2)

[1 2 3 4 5 6 7 8 9]


In [4]:
print(np.zeros(3))
print(np.ones(7))

[0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]


In [5]:
np.linspace(1,10,19)


array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

## 2d array 
- 2d array is a collection of data elements arranged in rows and columns.
- 2d array is also called as matrix.

In [6]:
arr4 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(np.zeros((2,3)))
print(arr4)

arr5 = np.arange(1,31).reshape(3,2,5)
print(arr5)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


In [7]:
arr6 = np.random.randint(0,60,(6,10))
# .reshape(5,2)
arr6

array([[38, 44, 31, 51, 56,  2, 59, 42,  4, 24],
       [ 3, 25, 57,  7, 34,  5, 46, 53, 38, 13],
       [12, 51, 18, 43, 33, 55, 38, 38, 59, 21],
       [53, 31, 25, 53, 39,  6, 35, 16, 42,  3],
       [31, 42, 24, 57, 33, 48, 28, 34, 48, 19],
       [45, 41, 59, 56,  0, 30, 20, 14, 55, 17]])

In [8]:
arr7 = np.arange(60).reshape(12,5)
print(arr7)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


In [9]:
arr7.shape # retruns the shape of array in tuple
arr4.dtype # datatype of elements of array
arr6.ndim # dimentions of array
arr7.size # returns number of total elements row*column*dim

60

In [10]:
arr8 = np.arange(1,100).reshape(3,3,11)
# arr9 = arr8.flatten()
arr8.T # to transpose the n-D array

array([[[ 1, 34, 67],
        [12, 45, 78],
        [23, 56, 89]],

       [[ 2, 35, 68],
        [13, 46, 79],
        [24, 57, 90]],

       [[ 3, 36, 69],
        [14, 47, 80],
        [25, 58, 91]],

       [[ 4, 37, 70],
        [15, 48, 81],
        [26, 59, 92]],

       [[ 5, 38, 71],
        [16, 49, 82],
        [27, 60, 93]],

       [[ 6, 39, 72],
        [17, 50, 83],
        [28, 61, 94]],

       [[ 7, 40, 73],
        [18, 51, 84],
        [29, 62, 95]],

       [[ 8, 41, 74],
        [19, 52, 85],
        [30, 63, 96]],

       [[ 9, 42, 75],
        [20, 53, 86],
        [31, 64, 97]],

       [[10, 43, 76],
        [21, 54, 87],
        [32, 65, 98]],

       [[11, 44, 77],
        [22, 55, 88],
        [33, 66, 99]]])

In [11]:
arr[::-1]


array([4, 3, 2, 1])

### slicing in Multidimensional array
- Slicing in multidimensional array is similar to slicing in 1d array.
- The only difference is that we need to specify the row and column index.
- The syntax for slicing in multidimensional array is as follows:
```python
array[row_start:row_end, column_start:column_end]
```
- The row_start and row_end are the starting and ending index of the rows.
- The column_start and column_end are the starting and ending index of the columns.
- The row_start and column_start are inclusive and the row_end and column_end are exclusive.
- The row_start and column_end are optional.
- If we do not specify the row_start and column_start, then it will take the default value as 0.
- If we do not specify the row_end and column_end, then it will take the default value as the length of the array.
- The row_end and column_end are exclusive.
- The row_start and column_start are inclusive.
- ex -
```python
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[0:2, 1:3])
```
- The above code will print the following output:
```
[[2 3]
 [5 6]]
```

In [12]:
arr5[:2,:2,:3:2]


array([[[ 1,  3],
        [ 6,  8]],

       [[11, 13],
        [16, 18]]])

In [13]:
# creating a 3D array
array3D = np.arange(1,201).reshape(4,5,10)
array3D

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]],

       [[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
        [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
        [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
        [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
        [141, 142, 143, 144, 145, 146, 147, 148, 149, 150]],

       [[151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
        [161, 162, 163, 164, 165, 

In [14]:
# print(array3D[:-1,:-2,-5:])
print(array3D[:,:1,2:3])
print(array3D[:,::-1,::-1])

[[[  3]]

 [[ 53]]

 [[103]]

 [[153]]]
[[[ 50  49  48  47  46  45  44  43  42  41]
  [ 40  39  38  37  36  35  34  33  32  31]
  [ 30  29  28  27  26  25  24  23  22  21]
  [ 20  19  18  17  16  15  14  13  12  11]
  [ 10   9   8   7   6   5   4   3   2   1]]

 [[100  99  98  97  96  95  94  93  92  91]
  [ 90  89  88  87  86  85  84  83  82  81]
  [ 80  79  78  77  76  75  74  73  72  71]
  [ 70  69  68  67  66  65  64  63  62  61]
  [ 60  59  58  57  56  55  54  53  52  51]]

 [[150 149 148 147 146 145 144 143 142 141]
  [140 139 138 137 136 135 134 133 132 131]
  [130 129 128 127 126 125 124 123 122 121]
  [120 119 118 117 116 115 114 113 112 111]
  [110 109 108 107 106 105 104 103 102 101]]

 [[200 199 198 197 196 195 194 193 192 191]
  [190 189 188 187 186 185 184 183 182 181]
  [180 179 178 177 176 175 174 173 172 171]
  [170 169 168 167 166 165 164 163 162 161]
  [160 159 158 157 156 155 154 153 152 151]]]
